* 最倒霉的一次

** 事发原因

看到Emacs China上有坛友轻轻松松通过 ctex 宏包 [[https://emacs-china.org/t/emacs-org-mode-inline-latex/27450/11][成功案例]]，而且还能成功完成 \( \begin{vmatrix} \textbf{xdv} \to \textbf{svg} \\ pdf \to svg  \end{vmatrix} \) 这样的在XeTeX上几乎不可能完成的操作。

BYD 反正我自己前两天折腾了6个小时，嗯是不可能绕过 pdf，于是放弃了，损失点性能就损失点性能吧，于是使用了 pdf2svg 来进行 pdf to svg。

不过倒是很羡慕他可以通过使用 ctex 宏包，渲染中文LaTeX片段 ~(´_>)~

但 ctex.sty 的大名岂不是浪得虚名的，我对 ctex 宏包的最大印象就是

#+begin_example
ctex.sty was not found!
#+end_example

但是看到坛友轻轻松松就能使用 ctex 来分别渲染中文与西文，于是按耐不住心情，还是尝试去配置了 ~(´_>)~

首先我必须声明一点的是，我是LaTeX萌新 ~( >﹏<。)~ 可能很多东西都没有那种使用了十几年的佬那么强

然后因为在我个人的配置情况下，使用org-latex-preview，(在我个人的配置下)它是不支持 ~\\usepackage{xeCJK}~ 的

org-latex-preview 它只支持 ~\\usepackage{fontspec}~ 只能设置 ~\\setmainfont{}, \\setsansfont{}, \\setmonofont{}~

(早知道我就不折腾了，弄了那么多最后还是回到原点，还弄得一身麻烦 ~´_>~ )

于是还是去折腾了 ctex，即往 org-preview-latex-process-alist 里面添加了 ~:latex-header "......  \\usepackage{ctex}  ........"~ 的设置

然后就是理所当然的 ~File /tmp/1145141919810.svg was not produced. Please adjust xxxxxxx~ 的错误提示了。

这当然啊，因为

#+begin_example
ctex.sty was not found!
#+end_example

然后我想那还是回归到 ctex 的问题上，于是接下来就惹到了一身麻烦了。

** 事情经过

*** 折腾 ctex 导致 LaTeX 本地环境全部爆炸(未知原因)

然后理所当然的就是 ~tlmgr install ctex~ 对吧？这是 TeXLive 的安装宏包的方式没错吧？

然后得到的回应就是 *ctex.sty is already exist!* 然后不让我重新安装。

然后我就千方百计地找到了 *搜索ctex的命令: tlmgr search --global* 啥啥啥的

然后它告诉我说在 ~/usr/share/texmf-dist/什么public/什么fonts/~ 下面

然后我就去那寻找，并且 ~ls ctex/ctex.sty~ 得到的消息居然是 *ls: 无法访问 'ctex/ctex.sty': 没有那个文件或目录* (我当时看到这里都气笑了😁)

然后我就让 tlmgr 强制安装: ~tlmgr install ctex --reinstall~

*结果您猜怎么着？BYD它给我报了满屏幕的Perl错误*

#+begin_example
首先，我在思考，这个包不是您们在维护的吗？怎么到头来居然是我刚安装不到2个星期的ArchLinux有问题呢？~¯\_(ツ)_/¯~
#+end_example

*而且还不止，在它终于结束了 ~tlmgr install ctex --reinstall~ 后，它提示说 *什么什么An error occured* 的

*然后我这个时候，才发现我的LaTeX本地环境全！部！都！爆！炸！了！*

*并且我还检查了 ~/usr/share/texmf-dist/什么public/什么fonts/~ 下，只有 ctex 文件夹，没有 ctex.sty！*

*最后我还重装了次新的 TexLive ~sudo pacman -S texlive~ 结果您猜怎么着？它在安装钩子运行时有几个钩子执行不了，说是什么什么错误*

所以这下完了，org-latex-preview 彻底不能用了

甚至连西文比如 \\( f(x) = 11451 \\) 的片段都是 ~File /tmp/1145141919810.svg was not produced. Please adjust xxxxxxx~ 了

这下我才知道我当时的处境是什么: *不管我再怎么发癫，也不可能把系统还原到折腾 ctex.sty 之前的情况了*


*** 深夜用着血丝遍布的眼睛，导致重装系统导致忘记了一步(我的原因)

于是我火速 ~rufus~ 了3月镜像，并靠着龟速的小水管手机热点

终于是在凌晨2点多时 *顶着笔记本caps、tab、~、esc键的全部失灵的压力* 嗯是完成了新的系统的安装。

*小提示: 虽然tab键坏了bash补不了全是没错，但我们还有 C-i 呀！👍*

真鸡2累，我自己因为 ctex.sty 我已经把我本该是玩游戏的时间、本该是用来休息的时间、本该是用来娱乐的时间，全部浪费在这些无用的地方上了

然而这个时候我发现了一个严重的问题，因为我实在是太累了，我忘记了重新设置 ~LANG=zh_CN.UTF-8~

这就导致了几乎所有的应用认定了必须使用英文路径比如 ~/home/user/Desktop~ 而不是 ~/home/user/桌面~

这就导致了非常严重的问题，我的emacs配置文件里有些变量是写死的，如果我硬是要改的话，请问我得改到多久？

而且就算 emacs 可以改，那请问别的应用呢？可以改吗？答案是: 都不可以改

比如 firefox 在那样的条件下，是一定认死了是 ~/home/user/Downloads~ 而不是 ~/home/user/下载~

即使自己mv了，即使自己重新设置了浏览器选项，仍然是 ~/home/user/Downloads~ 而不是 ~/home/user/下载~

这时我就头皮发麻了，那这么说来，还是要重新设置 ~LANG=zh_CN.UTF-8~

*** 赖在电脑上3年都不肯走的赛博牛皮藓，最后同归于尽全部一键清空(另类发行版的原因)

然后我必须要重装系统了，于是回到 Windows 10 的磁盘分区那里，默默删除深夜刚安装的系统

然后我自己回到 bios/uefi 那里，忽然看到了一张名为 “closeSuSE” 赛博牛皮藓(nickname)，因为过去发生的一些社区事情，导致现在的我自己看它非常不爽

于是先尝试了 Windows 10 的 bcdedit 工具，没用

然后再尝试了 bios/uefi 的原厂提供的删除引导文件功能，也没用

BYD我就怒了😡，于是立即 ~Windows Media Tools~ 启动

而且在等待U盘介质文件的安装过程中，我自己也看着那些3年前笔记本的文件，不由得感慨: *过去的我怎么会这么愚蠢呀！🌿*

于是 *算是需要清理赛博牛皮藓的需要吧，也算是对自己过去过于愚蠢的正式告别吧*

于是就在 Windows 10 磁盘分区下，点着一个一个分区的删除后，这下终于将自己先前过于愚蠢的一切都可以说是全部灰飞烟灭了。😊

包括那种看着非常不爽的赛博牛皮藓，包括自己过去3年过于愚蠢留下的痕迹。

然后这个时候已经凌晨3点多了，我就先睡觉了。


*** 刚醒来甚至都没有刷牙就开干，导致差点变砖(我的原因)

我愿称，今天为个人大脑的进行了超量级并发的一天。

于是只睡了5个多小时我就立即起来，甚至牙都没有刷，眼睛都是迷糊的~(´_>)~ 然后开始弄

然后因为眼睛迷迷糊糊的，忘记了挺重要的一步 ~grub-mkconfig -o /boot/grub/grub.cfg~

导致进入系统后，直接进入了 *grub* 模式。

然后当时看到这个画面时，我心里的各种紧张不安感慢慢涌起来。

然后在尝试了几个命令后，我忽然意识到，这下情况怎么这么像 *那张赛博牛皮藓导致的同款grub问题？*

#+begin_src
那次赛博牛皮藓导致的同款grub问题，是进入了 grub resure

而不是上面的grub，只是都是进入了grub界面而已，所以这次的非常好解决，但那次也就是下面所说的这次非常难以解决

我记得，当时我自己是因为什么问题，需要重装那张赛博牛皮藓对应的发行版，然后就去Windows磁盘分区那里删除了所在磁盘

但我忘记了重要的一点是: 我忘记了在 bios/uefi 里调整引导文件的加载顺序

于是，当时重装那张赛博牛皮藓对应的发行版，就排在了加载的第一位。

所以我那次在重启电脑后，跳过了 bios/uefi，直接就进入了grub resure救援模式。

在 [电源键按下，到出现grub resure界面] 的过程中

我无法按下任何键进入 bios/uefi！我无法通过 U 盘安装新系统！我无法通过 WinPE或LiveCD 修复！

这就是最恐怖的地方！！它貌似就是必须跟你说：“你必须先给我找到你的赛博牛皮藓对应的发行版系统，你才能过去，否则，一切免谈！！！！！！！！！！！”

然后我折腾了很久很久，当时2023年7月左右最后的解决方法是

+ 使用另一台设备，将赛博牛皮藓对应的发行版系统安装到U盘上

+ 并等待漫长的安装过程，约3小时左右，最主要还是那赛博牛皮藓并发下载与网速非常慢非常弱导致的

+ 在出现问题的电脑上，先插入u盘，然后电源键启动

然后我才能成功进入到那张赛博牛皮藓对应的发行版系统！

然后我检查了一下，我的 Windows 10 系统还在不在，答案是: 在的，而且完完整整好好的。

于是我立即调整引导文件加载顺序，这件事才过去。

这件事足足折腾了我连续20多个小时，我那次又通宵了。
#+end_src

话说回来，然后到现在的 *进入了grub* 而不是进入了grub resure 这里。

我突发奇想，输入了 exit，结果就直接进入了 Windows 10 系统。

“啊原来是这样啊，那看来没事了。” 看到输入命令后进入了 Windows 10 系统的我，舒了一口长气。

然后就是重新安装，重新认认真真、完完整整地走了一遍。

最后是折腾到今天下午4点左右，终于是全部都弄回来了。

【想到这里，我平时最喜欢吃的 *滑蛋牛肉饭、焖五花肉、烧鸡翅* 都因为这个原因，导致没时间做呢 ~( >﹏<。)~】

** 个人教训

从此我再也不敢再弄 ~ctex.sty~ 了 ~(´_>)~

现在我自己最终还是回到了原点 ~\\usepackage{fontspec} 的 \\setmainfont{}, \\setsansfont{}, \\setmonofont{}~ 

现在我看着这些一切都运行得很好的程序，真的产生了一种：被外面的狂风暴雨击打得踉踉跄跄地回到家，洗了一次彻底的热水澡，然后窝在温暖的小窝喝着热水吃着东西，那样在慢慢恢复的感觉。~(´_>)~

